# Generated by Django 2.2 on 2020-09-28 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noggins', '0003_noggin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NogginLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('noggin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noggins.Noggin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='noggin',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='noggin_user', through='noggins.NogginLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
