# Generated by Django 2.2 on 2020-10-11 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0005_noggin_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noggin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noggins', to=settings.AUTH_USER_MODEL),
        ),
    ]
