# Generated by Django 2.2 on 2020-10-12 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0006_auto_20201010_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='noggin',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
