# Generated by Django 2.2 on 2020-10-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0007_noggin_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noggin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
