# Generated by Django 2.2 on 2020-10-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0008_auto_20201020_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noggin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
