# Generated by Django 2.2 on 2020-10-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0009_auto_20201021_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noggin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
