# Generated by Django 2.2 on 2020-10-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0010_auto_20201022_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noggin',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noggins.Noggin'),
        ),
    ]
