# Generated by Django 2.2 on 2020-10-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0011_auto_20201024_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noggin',
            options={},
        ),
    ]
