# Generated by Django 2.2 on 2020-10-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0012_auto_20201029_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noggin',
            options={'ordering': ['-id']},
        ),
    ]
