# Generated by Django 2.2 on 2020-10-30 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0013_auto_20201029_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noggin',
            options={'ordering': ['-timestamp']},
        ),
    ]
