# Generated by Django 2.2 on 2020-10-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0014_auto_20201029_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noggin',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
