# Generated by Django 2.2 on 2020-10-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0015_auto_20201029_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noggin',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
