# Generated by Django 2.2 on 2020-10-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0017_auto_20201030_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noggin',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
