# Generated by Django 2.2 on 2020-10-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0018_auto_20201030_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noggin',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
