# Generated by Django 2.2 on 2020-10-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0020_auto_20201031_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noggin',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
