# Generated by Django 2.2 on 2020-11-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0023_auto_20201105_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nogginlike',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
