# Generated by Django 2.2 on 2020-11-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noggins', '0025_auto_20201116_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='noggin',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
