# Generated by Django 2.2 on 2020-11-19 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noggins', '0026_noggin_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentlike',
            field=models.ManyToManyField(blank=True, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
