# Generated by Django 2.2 on 2020-10-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20201026_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/basenoggin.png', null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
