# Generated by Django 2.2 on 2020-11-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20201027_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
