# Generated by Django 2.2 on 2020-11-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='noggintag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
