# Generated by Django 2.2 on 2020-11-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20201113_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/parking/chillen.png', null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
