# Generated by Django 2.2 on 2020-11-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20201115_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/parking/test.png', null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='noggintag',
            field=models.CharField(blank=True, default='PleaseCreateYourTag', max_length=90, null=True),
        ),
    ]
