# Generated by Django 2.2 on 2020-12-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20201203_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='noggintag',
        ),
    ]
