# Generated by Django 2.2 on 2020-12-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_profile_noggintag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerRelation',
        ),
    ]
